#!/bin/bash

set -e
#==================================
# natick Build System - Executable 
#==================================
# Copyright (C) 2018-2021 AJ Barris (AwlsomeAlex)
# aj at awlsome dot com
# ISC License - All Rights Reserved
#==================================

# Source natick Build System libraries
source ./nbs.lib
source ./build.lib

# build_toolchain: Generates the musl-libc toolchain
function build_toolchain {
    for pkg in musl-headers binutils gmp isl mpc mpfr gcc libgcc libstdc++-v3 libgomp pkgconf linux; do
        build_host_package ${pkg}
    done
}

# main: natick Build System execution point
function main() {
    # Match Command Argument
    case "${COMMAND}" in
        toolchain)
            setup_host_variables
            setup_build_system
            build_toolchain
            ;;
        help | *)
            show_usage
            ;;
    esac
}

main

