#!/bin/sh
# vim: tabstop=4: shiftwidth=4: expandtab: set filetype=bash:
##########################
#------------------------#
# MuroINIT - Service End #
#------------------------#
##########################
# rcE - Service End
#########################
# Copyright (C) 2019-2020 Alexander Barris - All Rights Reserved
# ISC License
# vGIT

for i in /etc/init.d/S??* ;do
    [ ! -f "$i" ] && continue
    case "$i" in
    *.sh)
        # Shell Script
        (
        trap - INT QUIT TSTP
        set stop
        . $i
        )
        ;;
    *)
        # Fork
        $i stop
        ;;
    esac
done
