#!/bin/sh
# vim: tabstop=4: shiftwidth=4: expandtab: set filetype=bash:
#============================#
# midstreams - natickOS INIT #
#----------------------------#
# init.d Function            #
# ISC License                #
#============================#
# Service End
#============================#
# Copyright (C) 2019-2021 Alexander Barris (AwlsomeAlex)
# alex@awlsome.com
# All Rights Reserved
#============================#


for i in /etc/init.d/S??* ;do
    [ ! -f "$i" ] && continue
    case "$i" in
    *.sh)
        # Shell Script
        (
        trap - INT QUIT TSTP
        set stop
        . $i
        )
        ;;
    *)
        # Fork
        $i stop
        ;;
    esac
done
