#!/bin/sh
# vim: tabstop=4: shiftwidth=4: expandtab: set filetype=bash:
##############################
#----------------------------#
# MuroINIT - Network Service #
#----------------------------#
##############################
# Network Service
##############################
# Copyright (C) 2019-2020 Alexander Barris - All Rights Reserved
# ISC License
# vGIT

#-------------------------#
# ----- Color Codes ----- #
#-------------------------#
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'


case "$1" in
    start)
        echo -e "${BLUE}[....] ${NC}Starting Network Devices...."
        for DEVICE in /sys/class/net/* ; do
            ip link set ${DEVICE##*/} up
            echo -e "${GREEN}[DONE] ${NC}Started Network Device ${DEVICE##*/}"
            [ ${DEVICE##*/} = wlan0 ] && wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf
			[ ${DEVICE##*/} != lo ] && [ ${DEVICE##*/} != sit0 ] && udhcpc -b -i ${DEVICE##*/} -s /etc/init.d/rc.udhcp
        done
        ;;
    stop)
        echo -e "${BLUE}[....] ${NC}Stopping Network Devices...."
        for DEVICE in /sys/class/net/* ; do
            ip link set ${DEVICE##*/} down
            echo -e "${GREEN}[DONE] ${NC}Stopped Network Device ${DEVICE##*/}"
        done
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage $0 {start|stop|restart}"
esac
exit $?
